/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminChatLogsRouteImport } from './routes/admin/chat-logs'
import { Route as ApiProjectsIndexRouteImport } from './routes/api/projects/index'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminConversationsRouteImport } from './routes/api/admin/conversations'
import { Route as ApiAdminContactsRouteImport } from './routes/api/admin/contacts'
import { Route as ApiAdminCheckAuthRouteImport } from './routes/api/admin/check-auth'
import { Route as ApiAdminContactsIdRouteImport } from './routes/api/admin/contacts.$id'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatLogsRoute = AdminChatLogsRouteImport.update({
  id: '/chat-logs',
  path: '/chat-logs',
  getParentRoute: () => AdminRoute,
} as any)
const ApiProjectsIndexRoute = ApiProjectsIndexRouteImport.update({
  id: '/api/projects/',
  path: '/api/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminConversationsRoute = ApiAdminConversationsRouteImport.update({
  id: '/api/admin/conversations',
  path: '/api/admin/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminContactsRoute = ApiAdminContactsRouteImport.update({
  id: '/api/admin/contacts',
  path: '/api/admin/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCheckAuthRoute = ApiAdminCheckAuthRouteImport.update({
  id: '/api/admin/check-auth',
  path: '/api/admin/check-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminContactsIdRoute = ApiAdminContactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminContactsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/chat-logs': typeof AdminChatLogsRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/api/contact': typeof ApiContactRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/check-auth': typeof ApiAdminCheckAuthRoute
  '/api/admin/contacts': typeof ApiAdminContactsRouteWithChildren
  '/api/admin/conversations': typeof ApiAdminConversationsRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/projects/': typeof ApiProjectsIndexRoute
  '/api/admin/contacts/$id': typeof ApiAdminContactsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/chat-logs': typeof AdminChatLogsRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/api/contact': typeof ApiContactRoute
  '/admin': typeof AdminIndexRoute
  '/api/admin/check-auth': typeof ApiAdminCheckAuthRoute
  '/api/admin/contacts': typeof ApiAdminContactsRouteWithChildren
  '/api/admin/conversations': typeof ApiAdminConversationsRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/projects': typeof ApiProjectsIndexRoute
  '/api/admin/contacts/$id': typeof ApiAdminContactsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/chat-logs': typeof AdminChatLogsRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/api/contact': typeof ApiContactRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/check-auth': typeof ApiAdminCheckAuthRoute
  '/api/admin/contacts': typeof ApiAdminContactsRouteWithChildren
  '/api/admin/conversations': typeof ApiAdminConversationsRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/projects/': typeof ApiProjectsIndexRoute
  '/api/admin/contacts/$id': typeof ApiAdminContactsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/chat-logs'
    | '/admin/login'
    | '/api/chat'
    | '/api/contact'
    | '/admin/'
    | '/api/admin/check-auth'
    | '/api/admin/contacts'
    | '/api/admin/conversations'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/projects/'
    | '/api/admin/contacts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/chat-logs'
    | '/admin/login'
    | '/api/chat'
    | '/api/contact'
    | '/admin'
    | '/api/admin/check-auth'
    | '/api/admin/contacts'
    | '/api/admin/conversations'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/projects'
    | '/api/admin/contacts/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/chat-logs'
    | '/admin/login'
    | '/api/chat'
    | '/api/contact'
    | '/admin/'
    | '/api/admin/check-auth'
    | '/api/admin/contacts'
    | '/api/admin/conversations'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/projects/'
    | '/api/admin/contacts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiAdminCheckAuthRoute: typeof ApiAdminCheckAuthRoute
  ApiAdminContactsRoute: typeof ApiAdminContactsRouteWithChildren
  ApiAdminConversationsRoute: typeof ApiAdminConversationsRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiProjectsIndexRoute: typeof ApiProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat-logs': {
      id: '/admin/chat-logs'
      path: '/chat-logs'
      fullPath: '/admin/chat-logs'
      preLoaderRoute: typeof AdminChatLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/projects/': {
      id: '/api/projects/'
      path: '/api/projects'
      fullPath: '/api/projects/'
      preLoaderRoute: typeof ApiProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/conversations': {
      id: '/api/admin/conversations'
      path: '/api/admin/conversations'
      fullPath: '/api/admin/conversations'
      preLoaderRoute: typeof ApiAdminConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/contacts': {
      id: '/api/admin/contacts'
      path: '/api/admin/contacts'
      fullPath: '/api/admin/contacts'
      preLoaderRoute: typeof ApiAdminContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/check-auth': {
      id: '/api/admin/check-auth'
      path: '/api/admin/check-auth'
      fullPath: '/api/admin/check-auth'
      preLoaderRoute: typeof ApiAdminCheckAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/contacts/$id': {
      id: '/api/admin/contacts/$id'
      path: '/$id'
      fullPath: '/api/admin/contacts/$id'
      preLoaderRoute: typeof ApiAdminContactsIdRouteImport
      parentRoute: typeof ApiAdminContactsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminChatLogsRoute: typeof AdminChatLogsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChatLogsRoute: AdminChatLogsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiAdminContactsRouteChildren {
  ApiAdminContactsIdRoute: typeof ApiAdminContactsIdRoute
}

const ApiAdminContactsRouteChildren: ApiAdminContactsRouteChildren = {
  ApiAdminContactsIdRoute: ApiAdminContactsIdRoute,
}

const ApiAdminContactsRouteWithChildren =
  ApiAdminContactsRoute._addFileChildren(ApiAdminContactsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiContactRoute: ApiContactRoute,
  ApiAdminCheckAuthRoute: ApiAdminCheckAuthRoute,
  ApiAdminContactsRoute: ApiAdminContactsRouteWithChildren,
  ApiAdminConversationsRoute: ApiAdminConversationsRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiProjectsIndexRoute: ApiProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
